import type { IconBaseProps } from "react-icons";
import {
  FaBook,
  FaBriefcase,
  FaChartBar,
  FaCode,
  FaDatabase,
  FaEnvelope,
  FaEye,
  FaGithub,
  FaGraduationCap,
  FaKey,
  FaLinkedin,
  FaMapMarkerAlt,
  FaServer,
  FaShoppingBag,
  FaTwitter,
  FaWrench,
} from "react-icons/fa";
import { IoSend } from "react-icons/io5";
import {
  SiDrizzle,
  SiEslint,
  SiExpress,
  SiFramer,
  SiGit,
  SiJavascript,
  SiJsonwebtokens,
  SiNextdotjs,
  SiNodedotjs,
  SiPnpm,
  SiPostgresql,
  SiPrettier,
  SiPrisma,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiShadcnui,
  SiSupabase,
  SiTailwindcss,
  SiTypescript,
  SiVercel,
  SiVite,
  SiZod,
} from "react-icons/si";

const icons: Record<string, React.ComponentType<IconBaseProps>> = {
  Github: FaGithub,
  Twitter: FaTwitter,
  Linkedin: FaLinkedin,
  Code2: FaCode,
  Server: FaServer,
  Database: FaDatabase,
  Wrench: FaWrench,
  Mail: FaEnvelope,
  MapPin: FaMapMarkerAlt,
  GraduationCap: FaGraduationCap,
  Briefcase: FaBriefcase,
  Eye: FaEye,
  BookText: FaBook,
  IoSend: IoSend,
  "Next.js": SiNextdotjs,
  "React.js": SiReact,
  "Tailwind CSS": SiTailwindcss,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  "Express.js": SiExpress,
  "Node.js": SiNodedotjs,
  "Framer Motion": SiFramer,
  "Shadcn UI": SiShadcnui,
  PostgreSQL: SiPostgresql,
  "TanStack Query": SiReactquery,
  Zod: SiZod,
  "React Hook Form": SiReacthookform,
  Supabase: SiSupabase,
  Prisma: SiPrisma,
  "Chart.js": FaChartBar,
  Drizzle: SiDrizzle,
  JWT: SiJsonwebtokens,
  Foodpanda: FaShoppingBag,
  Git: SiGit,
  Pnpm: SiPnpm,
  Vite: SiVite,
  EsLint: SiEslint,
  Prettier: SiPrettier,
  Vercel: SiVercel,
  "Context API": FaKey,
};

export function getIcon(name: string, props?: IconBaseProps) {
  const Icon = icons[name];

  return Icon ? <Icon {...props} /> : null;
}
